### ISSUE TITLE
Unable to install!

### ISSUE THREAD

**Issue by oltsa** [anorudes/mobx-easy-boilerplate#1]
Currently I'm unable to install, there is a lot of dependency mismatches

let's setup gitter or something

**Comment by anorudes** [comment]
Hello, @inertum. Which version of Node you are using?

**Comment by oltsa** [comment]
6.3

**Comment by oltsa** [comment]
Current setup wants different versions of webpack, try clean install with
cache clean

**Comment by anorudes** [comment]
It's working now, missing "mobx" dependence in package.json :D
